language: python

python:
  - '3.8.6'
  - '3.9-dev'

jobs:
  include:
    - &stage_deploy
      stage: deploy test
      if: NOT branch = main
      install:
        - pip install --upgrade pip
        - pip install twine build
      before-script:
        - python -m build .
        - twine check dist/*
      script:
        - twine upload --skip-existing --repository testpypi dist/*

    - <<: *stage_deploy
      stage: deploy prod
      if: branch = main
      script:
        - twine upload dist/*

install:
  - pip install --upgrade pip
  - pip install .[tests]
  - pip install coveralls

before_script:  # code coverage tool
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - flake8
  - black --diff --check .
  - mypy src
  - pytest --cov=zmfcli --cov-report=xml
  - coveralls
  - ./cc-test-reporter after-build
