language: python

python:
  - '3.8.6'
  - '3.9-dev'

install:
  - pip install --upgrade pip
  - pip install '.[tests]'

script:
  - flake8
  - black --check .
  - pytest --cov=zmfcli

after_success:
  - pip install coveralls
  - coveralls

jobs:
  include:
    - &stage_deploy
      stage: deploy test
      if: NOT branch = main
      install:
        - pip install --upgrade pip
        - pip install twine pep517
      before-script:
        - python -m pep517.check .
        - python -m pep517.build .
        - twine check dist/*
      script:
        - twine upload --skip-existing --repository-url https://test.pypi.org/legacy/ -u $PYPI_USER_TEST -p $PYPI_PWD_TEST dist/*
      after_success: skip
    - <<: *stage_deploy
      stage: deploy prod
      if: branch = main
      script:
        - twine upload --repository-url https://upload.pypi.org/legacy/ -u $PYPI_USER_PROD -p $PYPI_PWD_PROD dist/*
